{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "4fc24e28",
   "metadata": {},
   "source": [
    "\"\"\"\n",
    "Ingesta: carga los archivos fuente en el esquema `raw` de warehouse.duckdb.\n",
    "\n",
    "Estrategia: full refresh (CREATE OR REPLACE). La fuente es un snapshot completo,\n",
    "sin updated_at ni CDC.\n",
    "- CSV: todo como VARCHAR. El casteo y la validación se hacen en dbt (staging).\n",
    "- products.json: un registro por producto, tal cual viene.\n",
    "- fx_rates.json: una fila por respuesta de la API; `rates` se guarda como JSON\n",
    "  para no depender de qué monedas trae cada respuesta.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "36c14eff",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "from pathlib import Path\n",
    "import duckdb\n",
    "\n",
    "ROOT = Path(__file__).resolve().parents[1]\n",
    "DATA = ROOT / \"analytics_engineer_assets\"\n",
    "DB = ROOT / \"warehouse.duckdb\"\n",
    "\n",
    "CSV_SOURCES = {\n",
    "    \"customers\": \"customers.csv\",\n",
    "    \"orders\": \"orders.csv\",\n",
    "    \"order_items\": \"order_items.csv\",\n",
    "}\n",
    "\n",
    "\n",
    "def load_csv(con, table, fname):\n",
    "    path = (DATA / fname).as_posix()\n",
    "    con.execute(f\"\"\"\n",
    "        CREATE OR REPLACE TABLE raw.{table} AS\n",
    "        SELECT *,\n",
    "               current_timestamp AS _loaded_at,\n",
    "               '{fname}'         AS _source_file\n",
    "        FROM read_csv('{path}', header = true, all_varchar = true)\n",
    "    \"\"\")\n",
    "\n",
    "\n",
    "def load_products(con):\n",
    "    path = (DATA / \"products.json\").as_posix()\n",
    "    con.execute(f\"\"\"\n",
    "        CREATE OR REPLACE TABLE raw.products AS\n",
    "        SELECT *,\n",
    "               current_timestamp AS _loaded_at,\n",
    "               'products.json'   AS _source_file\n",
    "        FROM read_json_auto('{path}')\n",
    "    \"\"\")\n",
    "\n",
    "\n",
    "def load_fx_rates(con):\n",
    "    path = (DATA / \"fx_rates.json\").as_posix()\n",
    "    con.execute(f\"\"\"\n",
    "        CREATE OR REPLACE TABLE raw.fx_rates AS\n",
    "        WITH responses AS (\n",
    "            SELECT unnest(from_json(json(content) -> 'responses', '[\"JSON\"]')) AS resp\n",
    "            FROM read_text('{path}')\n",
    "        )\n",
    "        SELECT resp ->> 'base'    AS base_currency,\n",
    "               resp ->> 'date'    AS rate_date,\n",
    "               resp -> 'rates'    AS rates,\n",
    "               current_timestamp  AS _loaded_at,\n",
    "               'fx_rates.json'    AS _source_file\n",
    "        FROM responses\n",
    "    \"\"\")\n",
    "\n",
    "\n",
    "def main():\n",
    "    con = duckdb.connect(str(DB))\n",
    "    con.execute(\"CREATE SCHEMA IF NOT EXISTS raw\")\n",
    "\n",
    "    for table, fname in CSV_SOURCES.items():\n",
    "        load_csv(con, table, fname)\n",
    "    load_products(con)\n",
    "    load_fx_rates(con)\n",
    "\n",
    "    for (table,) in con.execute(\n",
    "        \"SELECT table_name FROM information_schema.tables \"\n",
    "        \"WHERE table_schema = 'raw' ORDER BY 1\"\n",
    "    ).fetchall():\n",
    "        n = con.execute(f\"SELECT count(*) FROM raw.{table}\").fetchone()[0]\n",
    "        print(f\"raw.{table}: {n} filas\")\n",
    "\n",
    "    con.close()\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
